name: Latest douban activities workflow
on:
  schedule:
    # Runs at 3:10 every day
    - cron: "10 3 * * *"

  issue_comment:
    types: [created, edited]

jobs:
  update-readme-with-douban-activities:
    name: Update this repo's README with douban activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md with douban user's activities
        uses: dongweiming/douban-activity-readme@v3
        with:
          uid: 153932994
          max_count: 10
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
